"use client";

import { useMemo, useRef, useState } from "react";

type Template = { id:string; name:string; use:string; width:number; height:number; defaultEyebrow:string; defaultTitle:string; defaultDetail:string; accent:"blue"|"white"|"dark" };

const templates: Template[] = [
  { id:"story-master", name:"Story Master", use:"Base flexible para comunicar", width:1080, height:1920, defaultEyebrow:"TECH STORE B&B", defaultTitle:"Tecnología que elegís con confianza.", defaultDetail:"Te asesoramos para que encuentres el equipo ideal para vos.", accent:"blue" },
  { id:"producto", name:"Producto", use:"Presentación clara de equipo", width:1080, height:1350, defaultEyebrow:"EQUIPO DESTACADO", defaultTitle:"Tu próximo equipo está acá.", defaultDetail:"Completá modelo, capacidad, color y condición antes de publicar.", accent:"white" },
  { id:"promocion", name:"Promoción", use:"Oferta con condiciones visibles", width:1080, height:1350, defaultEyebrow:"OPORTUNIDAD", defaultTitle:"Una propuesta pensada para vos.", defaultDetail:"Mostrá precio y vigencia solamente si están confirmados.", accent:"blue" },
  { id:"carrusel", name:"Carrusel educativo", use:"Consejos y comparativas", width:1080, height:1350, defaultEyebrow:"GUÍA TECH STORE", defaultTitle:"3 claves para elegir mejor.", defaultDetail:"Información simple, útil y sin vueltas. Deslizá para aprender.", accent:"dark" },
  { id:"reel", name:"Portada de Reel", use:"Título legible en el feed", width:1080, height:1920, defaultEyebrow:"EN 30 SEGUNDOS", defaultTitle:"Lo que tenés que saber antes de comprar.", defaultDetail:"Una idea por portada. Máximo impacto, mínimo ruido.", accent:"blue" },
  { id:"whatsapp", name:"WhatsApp Status", use:"Consulta rápida y directa", width:1080, height:1920, defaultEyebrow:"HABLEMOS", defaultTitle:"¿Buscás renovar tu equipo?", defaultDetail:"Contanos qué necesitás y te ayudamos a elegir.", accent:"white" },
  { id:"financiacion", name:"Precio / financiación", use:"Condiciones comerciales claras", width:1080, height:1350, defaultEyebrow:"OPCIONES DE COMPRA", defaultTitle:"Elegí cómo llevarlo.", defaultDetail:"Indicá monto, cuotas, medio de pago y vigencia confirmados.", accent:"blue" },
  { id:"unboxing", name:"Nuevo ingreso / unboxing", use:"Novedad sin falsa urgencia", width:1080, height:1920, defaultEyebrow:"NUEVO INGRESO", defaultTitle:"Mirá lo que llegó a Tech Store.", defaultDetail:"Mostrá el producto real y confirmá el stock antes de publicarlo.", accent:"dark" },
  { id:"canje", name:"Canje de equipos", use:"Explicar el proceso", width:1080, height:1350, defaultEyebrow:"PLAN CANJE", defaultTitle:"Tu equipo puede ser parte del pago.", defaultDetail:"Lo revisamos, lo cotizamos y te contamos tus opciones.", accent:"white" },
  { id:"equipo", name:"Local / equipo", use:"Confianza y cultura real", width:1080, height:1350, defaultEyebrow:"SOMOS TECH STORE", defaultTitle:"Personas que te ayudan a elegir.", defaultDetail:"Mostrá el local, el equipo y escenas reales de atención.", accent:"dark" },
];

const blue="#3C7AC3", dark="#252527";
function wrapText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number,lineHeight:number,maxLines=5){const words=text.trim().split(/\s+/),lines:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>max&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+Math.min(lines.length,maxLines)*lineHeight}

export default function Home(){
  const [selected,setSelected]=useState(templates[0].id); const template=useMemo(()=>templates.find(i=>i.id===selected)!,[selected]);
  const [eyebrow,setEyebrow]=useState(template.defaultEyebrow),[title,setTitle]=useState(template.defaultTitle),[detail,setDetail]=useState(template.defaultDetail);
  const [product,setProduct]=useState(""),[price,setPrice]=useState(""),[finance,setFinance]=useState(""),[cta,setCta]=useState("Escribinos y te asesoramos"),[photo,setPhoto]=useState("");
  const fileRef=useRef<HTMLInputElement>(null);
  const switchTemplate=(next:Template)=>{setSelected(next.id);setEyebrow(next.defaultEyebrow);setTitle(next.defaultTitle);setDetail(next.defaultDetail);setProduct("");setPrice("");setFinance("");setPhoto("")};
  const onPhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(file)};
  const exportPng=async()=>{const canvas=document.createElement("canvas");canvas.width=template.width;canvas.height=template.height;const ctx=canvas.getContext("2d")!;ctx.fillStyle=template.accent==="white"?"#F5F7FA":dark;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle=blue;ctx.fillRect(0,0,28,canvas.height);ctx.fillRect(0,0,canvas.width,22);ctx.globalAlpha=.16;ctx.beginPath();ctx.arc(canvas.width*.88,canvas.height*.16,canvas.width*.38,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(photo){const img=new Image();img.src=photo;await img.decode();const boxY=Math.round(canvas.height*.37),boxH=Math.round(canvas.height*.34),scale=Math.max(canvas.width/img.width,boxH/img.height),sw=canvas.width/scale,sh=boxH/scale;ctx.drawImage(img,(img.width-sw)/2,(img.height-sh)/2,sw,sh,0,boxY,canvas.width,boxH);ctx.fillStyle="rgba(37,37,39,.18)";ctx.fillRect(0,boxY,canvas.width,boxH)}const ink=template.accent==="white"?dark:"#FFFFFF";ctx.fillStyle=blue;ctx.font="700 30px Arial";ctx.fillText(eyebrow.toUpperCase(),92,124);ctx.fillStyle=ink;ctx.font=`800 ${template.height>1500?86:72}px Arial`;const afterTitle=wrapText(ctx,title,92,template.height*.19,canvas.width-184,template.height>1500?98:82,4);if(product){ctx.fillStyle=blue;ctx.font="800 44px Arial";wrapText(ctx,product,92,Math.max(afterTitle+26,template.height*.72),canvas.width-184,52,2)}let y=template.height*.78;ctx.fillStyle=ink;ctx.font="400 32px Arial";y=wrapText(ctx,detail,92,y,canvas.width-184,42,3)+24;if(price){ctx.fillStyle=blue;ctx.font="800 52px Arial";ctx.fillText(price,92,y);y+=62}if(finance){ctx.fillStyle=ink;ctx.font="700 30px Arial";ctx.fillText(finance,92,y)}ctx.fillStyle=blue;ctx.fillRect(92,canvas.height-142,canvas.width-184,72);ctx.fillStyle="white";ctx.font="700 28px Arial";ctx.fillText(cta,126,canvas.height-96);ctx.fillStyle=ink;ctx.font="700 24px Arial";ctx.textAlign="right";ctx.fillText("TECH STORE B&B",canvas.width-92,canvas.height-28);const a=document.createElement("a");a.download=`tech-store-${template.id}-${template.width}x${template.height}.png`;a.href=canvas.toDataURL("image/png");a.click()};
  const previewStyle={"--ratio":`${template.width} / ${template.height}`} as React.CSSProperties;
  return <main><header className="topbar"><div className="brand"><span className="brandMark">TS</span><div><strong>Tech Store OS</strong><small>Production Templates · v1.3</small></div></div><div className="status"><span/> Sistema listo para producir</div></header>
    <section className="workspace"><aside className="library" aria-label="Biblioteca de plantillas"><div className="sectionHead"><p>01 / BIBLIOTECA</p><h1>Elegí una pieza</h1></div><div className="templateList">{templates.map((item,index)=><button key={item.id} className={item.id===selected?"template active":"template"} onClick={()=>switchTemplate(item)}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{item.name}</strong><small>{item.use}</small></div><i>{item.height>item.width*1.5?"9:16":"4:5"}</i></button>)}</div></aside>
    <section className="stage"><div className="stageHead"><div><p>02 / VISTA PREVIA</p><h2>{template.name}</h2></div><span>{template.width} × {template.height} px</span></div><div className="previewShell"><article className={`artboard ${template.accent}`} style={previewStyle}><div className="orb"/>{photo?<img src={photo} alt="Foto seleccionada"/>:<div className="photoGuide"><span>+</span><small>Tu foto real acá</small></div>}<div className="artContent"><b>{eyebrow}</b><h3>{title}</h3></div><div className="artBottom">{product&&<strong className="productName">{product}</strong>}<p>{detail}</p>{price&&<strong className="price">{price}</strong>}{finance&&<small className="finance">{finance}</small>}<div className="cta">{cta}</div><em>TECH STORE B&B</em></div></article></div></section>
    <aside className="editor"><div className="sectionHead"><p>03 / CONTENIDO</p><h2>Completá la pieza</h2></div><label>Etiqueta<input value={eyebrow} onChange={e=>setEyebrow(e.target.value)} maxLength={32}/></label><label>Título<textarea value={title} onChange={e=>setTitle(e.target.value)} maxLength={110} rows={3}/></label><label>Producto / dato principal<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="Sólo información confirmada"/></label><label>Texto de apoyo<textarea value={detail} onChange={e=>setDetail(e.target.value)} maxLength={180} rows={3}/></label><div className="commercial"><div><span>Datos comerciales</span><small>Dejalos vacíos si no están confirmados</small></div><label>Precio<input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Ej.: $ —"/></label><label>Financiación<input value={finance} onChange={e=>setFinance(e.target.value)} placeholder="Cuotas + medio + vigencia"/></label></div><label>CTA<input value={cta} onChange={e=>setCta(e.target.value)} maxLength={45}/></label><input ref={fileRef} className="hiddenFile" type="file" accept="image/*" onChange={e=>onPhoto(e.target.files?.[0])}/><button className="photoButton" onClick={()=>fileRef.current?.click()}>{photo?"Cambiar foto":"Agregar foto real"}</button><div className="guardrail"><strong>Control de publicación</strong><p>✓ Sin datos inventados<br/>✓ Sin urgencia artificial<br/>✓ Sin testimonios no verificados</p></div><button className="export" onClick={exportPng}>Descargar PNG <span>↓</span></button></aside></section>
    <footer><span>Tech Store B&B · Sistema de producción v1.3</span><span>Azul #3C7AC3 · Dark #252527 · Blanco #FFFFFF</span></footer></main>
}
